<!--
  Heads up!
  This file is being managed by Gemini.
  To prevent conflicts, do not edit this file unless instructed.
-->
<div class="p-8">
  <h1 class="text-4xl font-bold">工作空间</h1>
  <p class="mt-4">文档列表页面正在建设中...</p>
</div>
