<!--
  Heads up!
  This file is being managed by Gemini.
  To prevent conflicts, do not edit this file unless instructed.
-->
<script lang="ts">
  import { onMount } from 'svelte';

  // TODO: Replace mock data with actual API call to /api/v1/auth/config
  const mockProviders = [
    { name: 'Nyarime SSO', ssoUrl: '/api/v1/auth/login/nyarime' },
    { name: 'GitHub', ssoUrl: '/api/v1/auth/login/github' }
  ];

  let oidcProviders: Array<{ name: string; ssoUrl: string }> = [];
  let isLoading = true;
  let error: string | null = null;

  onMount(async () => {
    try {
      // Simulate network delay
      await new Promise((resolve) => setTimeout(resolve, 750));
      // In a real scenario, you would fetch from the API:
      // const response = await fetch('/api/v1/auth/config');
      // if (!response.ok) {
      //   throw new Error('无法获取 OIDC 配置');
      // }
      // const data = await response.json();
      // oidcProviders = data.providers || [];
      oidcProviders = mockProviders;

      if (oidcProviders.length === 0) {
        // Handle case where no providers are configured
      }
    } catch (e: any) {
      error = e.message;
      console.error('获取 OIDC 配置失败:', e);
    } finally {
      isLoading = false;
    }
  });
</script>

<div
  class="w-full rounded-2xl p-8 border-2 min-h-48"
>
    <h1 class="text-3xl font-semibold mb-4 py-2 text-gray-700 dark:text-gray-300">OIDC 登录</h1>
  {#if isLoading}
    <div
      class="flex w-full h-full items-center justify-center rounded-xl"
    >
      <p class="text-gray-500 dark:text-gray-400 py-4 h-24">正在加载登录选项...</p>
    </div>
  {:else if error}
    <div class="text-center text-red-500">
      <p>登录时发生错误:</p>
      <p class="font-mono text-sm">{error}</p>
      <!-- You could offer a fallback login method here -->
    </div>
  {:else if oidcProviders.length > 0}
    <div class="flex flex-col space-y-4 py-2">
      {#each oidcProviders as provider, i}
        <a
          href={provider.ssoUrl}
          class="block w-full rounded-xl py-3 px-6 text-center text-base font-medium shadow-sm transition-shadow hover:shadow-lg {i === 0
            ? 'bg-riptide-500 text-riptide-50'
            : 'bg-white text-gray-600 dark:bg-slate-700 dark:text-gray-300'}"
        >
          使用 {provider.name} 登录
        </a>
      {/each}
    </div>
  {:else}
    <div class="text-center text-gray-500 dark:text-gray-400">
      <p>当前没有可用的 SSO 登录选项。</p>
      <p class="mt-2 text-sm">请联系您的管理员进行配置。</p>
    </div>
  {/if}
</div>

