<!--
  Heads up!
  This file is being managed by Gemini.
  To prevent conflicts, do not edit this file unless instructed.
-->
<div
  class="flex h-48 w-full items-center justify-center rounded-lg border-2 border-dashed border-gray-300 bg-white p-8 dark:border-gray-600 dark:bg-slate-800"
>
  <p class="text-gray-500 dark:text-gray-400">OIDC 登录</p>
</div>

