<!--
  Heads up!
  This file is being managed by Gemini.
  To prevent conflicts, do not edit this file unless instructed.
-->
<div
	class="flex min-h-screen flex-col items-center justify-center bg-riptide-50 p-8 text-center dark:bg-slate-800"
>
	<h1 class="text-3xl font-bold sm:text-4xl md:text-6xl">
		<span class="bg-gradient-to-r from-cyan-300 to-yellow-300 bg-clip-text text-transparent">
			CyimeWrite
		</span>
		<span class="text-gray-800 dark:text-gray-200">青柠写</span>
	</h1>
	<p class="mt-4 text-base text-gray-600 dark:text-gray-400 md:text-xl">
		轻量简洁的云端同步Markdown编辑器，<br>为随心流动的创意而生
	</p>
	<div class="mt-8 flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
		<button
			class="rounded-lg bg-riptide-500 py-3 px-6 font-semibold shadow-lg transition-shadow hover:shadow-xl text-riptide-50"
		>
			开始写作
		</button>
		<a
            href="#features"
			class="rounded-lg bg-white py-3 px-6 font-semibold text-gray-600 shadow-lg transition-shadow hover:shadow-xl dark:bg-slate-700 dark:text-gray-300"
		>
			了解更多
		</a>
	</div>
</div>

<!-- Features Section -->
<div id="features" class="space-y-16 py-16 md:space-y-28 md:py-28">
	<!-- Feature 1: Online Sync -->
	<section class="bg-white px-8 dark:bg-slate-900">
		<div class="mx-auto max-w-5xl">
			<div class="flex flex-col items-center gap-8 md:flex-row md:gap-8">
				<div class="w-full md:w-1/2">
					<div
						class="aspect-video w-full rounded-2xl bg-gray-200 shadow-lg dark:bg-slate-700"
						aria-label="编辑器功能截图"
					></div>
				</div>
				<div class="w-full text-center md:w-1/2 md:pl-16 md:text-left">
					<h2
						class="text-2xl font-bold text-gray-800 dark:text-gray-200 sm:text-3xl md:text-4xl"
					>
						在线同步写作体验
					</h2>
					<p class="mt-4 text-sm text-gray-600 dark:text-gray-400 md:text-lg font-light">
						无论身处何地，灵感永不丢失。所有内容实时云端同步，随时在浏览器、桌面或移动设备间无缝切换，继续你的创作。
					</p>
				</div>
			</div>
		</div>
	</section>

	<!-- Feature 2: Minimalist Interface -->
	<section class="bg-riptide-50 py-16 dark:bg-slate-800 md:py-28">
		<div class="mx-auto max-w-5xl px-8">
			<div class="flex flex-col items-center gap-8 md:flex-row-reverse md:gap-8">
				<div class="w-full md:w-1/2">
					<div
						class="aspect-video w-full rounded-2xl bg-gray-200 shadow-lg dark:bg-slate-700"
						aria-label="极简编辑器界面截图"
					></div>
				</div>
				<div class="w-full text-center md:w-1/2 md:pr-16 md:text-left">
					<h2
						class="text-2xl font-bold text-gray-800 dark:text-gray-200 sm:text-3xl md:text-4xl"
					>
						专注写作，零干扰
					</h2>
					<p class="mt-4 text-sm text-gray-600 dark:text-gray-400 md:text-lg font-light">
						我们相信，最好的工具是隐形的。简洁的界面设计，让你能完全专注于内容本身，心无旁骛地完成每一次书写。
					</p>
				</div>
			</div>
		</div>
	</section>

	<!-- Feature 3: Smooth Response -->
	<section class="bg-white px-8 dark:bg-slate-900">
		<div class="mx-auto max-w-5xl">
			<div class="flex flex-col items-center gap-8 md:flex-row md:gap-8">
				<div class="w-full md:w-1/2">
					<div
						class="aspect-video w-full rounded-2xl bg-gray-200 shadow-lg dark:bg-slate-700"
						aria-label="流畅输入动画"
					></div>
				</div>
				<div class="w-full text-center md:w-1/2 md:pl-16 md:text-left">
					<h2
						class="text-2xl font-bold text-gray-800 dark:text-gray-200 sm:text-3xl md:text-4xl"
					>
						流畅如本地编辑器
					</h2>
					<p class="mt-4 text-sm text-gray-600 dark:text-gray-400 md:text-lg font-light">
						基于最新的 Web
						技术构建，每一次按键都如丝般顺滑。享受毫秒级的响应速度，彻底告别云端编辑器的卡顿和粘滞感。
					</p>
				</div>
			</div>
		</div>
	</section>
</div>

<!-- Footer -->
<footer class="bg-gray-100 dark:bg-slate-700">
	<div class="mx-auto max-w-7xl py-12 px-4 text-center sm:px-6 lg:px-8">
		<p class="text-gray-500 dark:text-gray-300">© 2026 CyimeWrite. 保留所有权利。</p>
	</div>
</footer>
