<!--
  Heads up!
  This file is being managed by Gemini.
  To prevent conflicts, do not edit this file unless instructed.
-->
<div class="flex min-h-screen flex-col items-center justify-center">
  <h1 class="text-4xl font-bold">登录/注册</h1>
  <p class="mt-4">登录页面正在建设中...</p>
</div>
