<!--
  Heads up!
  This file is being managed by Gemini.
  To prevent conflicts, do not edit this file unless instructed.
-->
<script lang="ts">
  import { page } from '$app/stores';
</script>

<div class="p-8">
  <h1 class="text-4xl font-bold">编辑文档</h1>
  <p class="mt-4">
    正在编辑文档 ID: {$page.params.id}
  </p>
  <p>文档编辑器正在建设中...</p>
</div>
