<!--
  Heads up!
  This file is being managed by Gemini.
  To prevent conflicts, do not edit this file unless instructed.
-->
<script lang="ts">
  import { page } from '$app/stores';
  import * as m from '$paraglide/messages';
</script>

<div class="p-8">
  <h1 class="text-4xl font-bold">{m.edit_document_title()}</h1>
  <p class="mt-4">
    {m.edit_document_id_prefix()}: {$page.params.id}
  </p>
  <p>{m.edit_document_editor_under_construction()}</p>
</div>
